
server:
  port: ${PORT:8714}
spring:
  application:
    name: eureka-server
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8714/eureka/}
